version: '3.8'
services:
  canal-server:
    image: canal/canal-server:v1.1.6
    container_name: canal-server
    ports:
      - "11111:11111"
    environment:
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=root
      - canal.instance.filter.regex=.*\\.seckill_order
    depends_on:
      - mysql 