version: '3.8'
services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seckill
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password 

  skywalking-oap:
    image: apache/skywalking-oap-server:9.0.0
    ports:
      - "11800:11800"
      - "12800:12800"
    restart: always

  skywalking-ui:
    image: apache/skywalking-ui:9.0.0
    ports:
      - "8088:8080"
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
    depends_on:
      - skywalking-oap
    restart: always

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    restart: always

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./logs:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    restart: always

  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    ports:
      - "8858:8858"
    restart: always 