apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: seckill-service
  template:
    metadata:
      labels:
        app: seckill-service
    spec:
      containers:
        - name: seckill-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 