server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: seckill-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=UTC
        username: root
        password: root
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/seckill?useSSL=false&serverTimezone=UTC
        username: root
        password: root
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave
    sharding:
      tables:
        seckill_order:
          actual-data-nodes: ms.seckill_order_$->{0..3}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: seckill_order_$->{user_id % 4}
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql.show: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.flashsale.entity

# 灰度发布相关配置示例
feature:
  gray-release:
    enabled: true
    gray-users: 1001,1002,1003 