server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379 