server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://prod-mysql:3306/seckill_prod?useSSL=false&serverTimezone=UTC
    username: prod_user
    password: prod_pass
  redis:
    host: prod-redis
    port: 6379 